name: Curl API with Secret

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  curl-api:
    runs-on: ubuntu-latest
    steps:
      - name: Curl API with secret key
        run: |
          curl "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_API_KEY }}" -o apod.json
          HDURL=$(jq -r .hdurl apod.json)
          echo "HDURL=$HDURL" >> $GITHUB_ENV

      - name: Download HD image
        run: |
          curl "$HDURL" -o apod_hd.jpg

      - name: Upload HD image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nasa-apod-hd-image
          path: apod_hd.jpg
